// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca.Model.Models;

public partial class Livros
{
    public int LivroId { get; set; }

    public string Titulo { get; set; }

    public int? AnoPublicacao { get; set; }

    public int? AutorId { get; set; }

    public virtual Autores Autor { get; set; }
}